const fs = require('fs');

const path = require('path');

const PDFDocument = require('pdfkit');


const PRESCRIPTION_DIR = path.join(__dirname, '..', 'uploads', 'prescriptions');

const ORB_LOGO_PATH = path.join(__dirname, '..', 'assets', 'medidiagnose-orb.png');


const BRAND = {

  title: '#16a34a',

  subtitle: '#64748b',

  body: '#111827',

  muted: '#475569',

  divider: '#bbf7d0',

};


function ensureDir() {

  if (!fs.existsSync(PRESCRIPTION_DIR)) {

    fs.mkdirSync(PRESCRIPTION_DIR, { recursive: true });

  }

}


function drawOrbLogoFallback(doc, cx, cy, radius) {

  const layers = [

    { scale: 1.0, color: '#0e7490', opacity: 0.35 },

    { scale: 0.82, color: '#0891b2', opacity: 0.45 },

    { scale: 0.64, color: '#22d3ee', opacity: 0.55 },

    { scale: 0.46, color: '#67e8f9', opacity: 0.65 },

  ];


  doc.save();

  layers.forEach((layer) => {

    doc.circle(cx, cy, radius * layer.scale)

      .fillColor(layer.color)

      .fillOpacity(layer.opacity)

      .fill();

  });


  doc.circle(cx - radius * 0.22, cy - radius * 0.28, radius * 0.1)

    .fillColor('#ffffff')

    .fillOpacity(0.85)

    .fill();


  doc.circle(cx + radius * 0.3, cy + radius * 0.18, radius * 0.05)

    .fillColor('#fef08a')

    .fillOpacity(0.7)

    .fill();

  doc.restore();

}


function drawPdfHeader(doc) {

  const pageWidth = doc.page.width;

  const margin = doc.page.margins.left || 50;

  const contentWidth = pageWidth - margin * 2;

  const logoSize = 68;

  const headerTop = 34;

  const logoX = (pageWidth - logoSize) / 2;


  if (fs.existsSync(ORB_LOGO_PATH)) {

    doc.image(ORB_LOGO_PATH, logoX, headerTop, {

      width: logoSize,

      height: logoSize,

    });

  } else {

    drawOrbLogoFallback(

      doc,

      pageWidth / 2,

      headerTop + logoSize / 2,

      logoSize / 2

    );

  }


  const titleY = headerTop + logoSize + 16;


  doc.font('Helvetica-Bold')

    .fontSize(28)

    .fillColor(BRAND.title)

    .text('MediDiagnose', margin, titleY, {

      align: 'center',

      width: contentWidth,

    });


  doc.font('Helvetica')

    .fontSize(11)

    .fillColor(BRAND.subtitle)

    .text('Clinical Prescription', margin, titleY + 36, {

      align: 'center',

      width: contentWidth,

    });


  const dividerY = titleY + 62;

  doc.strokeColor(BRAND.divider)

    .lineWidth(1.5)

    .moveTo(margin + 48, dividerY)

    .lineTo(pageWidth - margin - 48, dividerY)

    .stroke();


  doc.fillColor(BRAND.body);

  doc.font('Helvetica').fontSize(11);

  doc.y = dividerY + 22;

}


function drawSectionTitle(doc, title) {

  doc.moveDown(0.4);

  doc.font('Helvetica-Bold')

    .fontSize(12)

    .fillColor(BRAND.title)

    .text(title);

  doc.moveDown(0.2);

  doc.font('Helvetica')

    .fontSize(11)

    .fillColor(BRAND.body);

}


async function generatePrescriptionPdf({

  sessionId,

  patientName,

  doctorName,

  finalDiagnosis,

  medications,

  instructions,

  icd10Code,

  icd10Display,

}) {

  ensureDir();

  const filename = `prescription_${sessionId}_${Date.now()}.pdf`;

  const filePath = path.join(PRESCRIPTION_DIR, filename);


  return new Promise((resolve, reject) => {

    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);


    drawPdfHeader(doc);


    doc.fillColor(BRAND.muted).text(`Date: ${new Date().toLocaleDateString()}`);

    doc.text(`Patient: ${patientName}`);

    doc.text(`Physician: Dr. ${doctorName}`);

    doc.fillColor(BRAND.body);


    drawSectionTitle(doc, 'Diagnosis');

    doc.text(finalDiagnosis || 'See clinical notes');


    drawSectionTitle(doc, 'Medications / Treatment');

    doc.text(medications || 'As clinically indicated');


    drawSectionTitle(doc, 'Instructions');

    doc.text(instructions || 'Follow up as needed.');


    doc.moveDown(2);

    doc.fillColor(BRAND.muted)

      .fontSize(10)

      .text('Electronically signed by attending physician.');

    doc.text(`Signed: Dr. ${doctorName}`);


    doc.fontSize(8)

      .fillColor('#94a3b8')

      .text(

        'Generated by MediDiagnose — AI-assisted medical diagnosis platform.',

        { align: 'center' }

      );


    doc.end();

    stream.on('finish', () => resolve({ filePath, filename }));

    stream.on('error', reject);

  });

}


module.exports = {

  generatePrescriptionPdf,

  PRESCRIPTION_DIR,

  ORB_LOGO_PATH,

};

